image: maven:latest

stages:
  - build
  - test
  - package

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    untracked: true

test:
  stage: test
  dependencies: 
    - build
  script:
    - mvn test
  artifacts:
    untracked: true

package:
  stage: package
  dependencies: 
    - test
  script:
    - mvn package
  only:
    - master
